version: '3.8'
services:
  app:
    container_name: nextjs-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://clickPhone:a5K69_7gS78b@db:5432/mydb
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

